### ISSUE TITLE
Bisher keine Korrektur des Praktikum 4. Es fehlt der Nachweis des Praktikums zu Java 2.

### ISSUE THREAD

**Issue by UrsulaOesing** [AbobakrAl-mahdi/PraktikumOOP#2]

**Comment by AbobakrAl-mahdi** [comment]
[notenspiegelInstudiengang139c3bd8-488f-4589-8e8f-8091e69d335c.pdf](https://github.com/AbobakrAl-mahdi/PraktikumOOP/files/7771476/notenspiegelInstudiengang139c3bd8-488f-4589-8e8f-8091e69d335c.pdf)
