### ISSUE TITLE
Bisher keine Korrektur des Praktikums 4.

### ISSUE THREAD

**Issue by UrsulaOesing** [AbobakrAl-mahdi/PraktikumOOP#3]

**Comment by AbobakrAl-mahdi** [comment]
![PraktOrg](https://user-images.githubusercontent.com/74077606/146825813-2a317753-dda1-4501-84ad-5e12a7b11124.JPG)
Ich Hoffe das Reicht als Nachweis. @UrsulaOesing

**Comment by AbobakrAl-mahdi** [comment]
[notenspiegelInstudiengang139c3bd8-488f-4589-8e8f-8091e69d335c.pdf](https://github.com/AbobakrAl-mahdi/PraktikumOOP/files/7771472/notenspiegelInstudiengang139c3bd8-488f-4589-8e8f-8091e69d335c.pdf)
